version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.0-alpine
    hostname: postgres
    environment:
      POSTGRES_DB: "TestDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5434:5432
    networks:
      - postgres

  #  TODO add entry point
  django_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - postgres
    command: 'python manage.py runserver 0.0.0.0:8000'

volumes:
  postgres_data:

networks:
  postgres: